version: '3.9'

services:
  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./FRONTEND:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    environment:
      - PYTHONUNBUFFERED=1